# Generated by Django 5.2.1 on 2025-05-09 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_add_indexes_to_foreign_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='essayanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('essay', 'Essay')], db_index=True, default='multiple_choice', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='draft',
            field=models.BooleanField(db_index=True, default=False, help_text='If yes, quiz is not displayed in the quiz list'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['user', 'quiz'], name='quiz_progre_user_id_323337_idx'),
        ),
    ]
